### ISSUE TITLE
Document Translation

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro#120]
We just finished most of translate jobs and published at [pro.ant.design](http://pro.ant.design), welcome to visit it and review the translation. Give us PR if you find any typos. 🎅 

---
## Volunteer Wanted

Hey, guys! We are going to provide English documentation. 

But we are short of staff :-( So, we want some volunteers to help us to translate antd's documentation into English. Every translation task needs a translator and a reviewer. Both of them are expected that they had used the component(`AvatarLsit` `PageHeader` etc...) in real world.
### Translator

A translator should be familiar with both Chinese and English. 

If you want to be a volunteer translator, just comment this issue. For example, "I want to be the translator of button and alert ....". And then, we will update this issue(e.g. button (translator: @afc163 , reviewer:  @ddcat1115 )), and ping you. 

Premise:
- [ant-design-pro-site](https://github.com/ant-design/ant-design-pro-site) is our site of Ant Design Pro and it is repository witch docs here.
- [ant-design-pro](https://github.com/ant-design/ant-design-pro) is [ant-design-pro-site](https://github.com/ant-design/ant-design-pro-site)'s submodule, it contains component's docs.

Contributing:
1. Fork 
    - docs: [ant-design-pro-site](https://github.com/ant-design/ant-design-pro-site) and `git clone`
    - components: [ant-design-pro](https://github.com/ant-design/ant-design-pro) and `git clone`
2. Create a branch starting at `master` and name it as `translation-[xxx]`
3. `npm install && npm start`, see: [Development](https://github.com/ant-design/ant-design-pro-site#development)
4. Find Markdown files and the `index.md` and `demo/*.md` use different format, see: https://github.com/ant-design/ant-design/issues/1423
    - docs: under `/docs`
    - components: under `/scaffold/src/components/xxx`(xxx is the component which you need to translate)
5. Just translate it, and you had better read our [advice](https://github.com/ant-design/ant-design/issues/1471#issuecomment-213636139) first.
6. Create a pull request when your translation is done, and ping your reviewer.
    -  docs: request to `ant-design-pro-site:master`
    -  components: request to `ant-design-pro:master` 
7. PR will be merged, if your reviewer think it is OK.

See: 
- https://github.com/ant-design/ant-design/tree/master/components/button
- https://github.com/ant-design/ant-design/blob/master/components/button/demo/basic.md

### Reviewer

A reviewer should be a native English speaker.

If you want to be a volunteer reviewer, just comment this issue. For example, "I want to be the reviewer of button and alert...". And then, we will update this issue(e.g. button (translator: @afc163 , reviewer:  @ddcat1115 )), and ping you. 

After your corresponding translator finish his/her work, you should review and provide some advice.

### Example

- docs: [105](https://github.com/ant-design/ant-design-pro-site/pull/105)
- components: [123](https://github.com/ant-design/ant-design-pro/pull/123)

### TODOs

/docs
- [x] api-doc.md ( translator: @yesmeck ) 
- [ ] authority-management.md ( translator: @chenshuai2144 ) 
- [ ] biz-icon.md ( translator: @ddcat1115 ) 
- [ ] changelog.md ( translator: @ddcat1115 ) 
- [x] cli.md ( translator: @viztor ) 
- [x] deploy.md  ( translator: @yesmeck ) 
- [ ] error.md ( translator: @nikogu )
- [ ] faq.md ( translator: null) 
- [x] getting-started.md
- [x] getting-start-inner.md
- [ ] graph.md (translator: @RaoHai)
- [x] i18n.md ( translator: @viztor ) 
- [ ] import.md ( translator: null) 
- [x] layout.md ( translator: @viztor ) 
- [ ] mock-api.md ( translator: @afc163 ) https://github.com/ant-design/ant-design-pro-site/pull/156
- [x] new-component.md ( translator: @afc163 ) https://github.com/ant-design/ant-design-pro-site/pull/157
- [x] new-page.md ( translator: @valleykid ) 
- [x] resource.md ( translator: @nikogu )
- [ ] router-and-nav.md ( translator: @ddcat1115 ) 
- [x] server.md ( translator: @valleykid ) 
- [x] style.md( translator: @yutingzhao1991 ) https://github.com/ant-design/ant-design-pro-site/pull/148
- [ ] theme.md ( translator: @nikogu )
- [ ] ui-test.md ( translator: @yutingzhao1991 ) https://github.com/ant-design/ant-design-pro-site/pull/151
- [x] use-components-alone.md ( translator: @dengfuping ) 

/components
- [x] AvatarList (translator: @nikogu)
- [ ] Charts (translator: @RaoHai)
- [x] CountDown (translator: @nikogu)
- [x] DescriptionList ( translator: @ddcat1115 ) 
- [x] Exception ( translator: @ddcat1115 ) 
- [x] FooterToolbar ( translator: @dengfuping ) 
- [ ] GlobalFooter ( translator: @MrPeak  ) 
- [ ] HeaderSearch ( translator: @MrPeak  ) 
- [ ] NoticeIcon ( translator: @MrPeak  ) 
- [x] NumberInfo
- [x] Ellipsis
- [ ] PageHeader
- [ ] Result
- [ ] TagSelect
- [ ] Trend
- [ ] Authorized ( translator: @chenshuai2144 ) 
- [ ] Login

**Comment by gardner** [comment]
Thanks for taking the time to translate the documentation!

This is really great. Our UX team brought Ant Design to us and asked if we could use this on a new project. The design and engineering decisions I have learned about across all of the ant design projects are amazing and I would love to use and participate but by ability to read or write Chinese is non-existent.

**Comment by afc163** [comment]
@tmattio @Kikobeats @viztor @acomito

**Comment by viztor** [comment]
@afc163 thanks for mentioning me
I might want to take getting started.

**Comment by viztor** [comment]
review needed for getting-started.md:
@gardner In case you might want to lend a helping hand.

**Comment by gardner** [comment]
@viztor all of the language was technically correct. I don't now how to explain it other than English with Chinese characteristics. There were a few things that were understandable but sounded non-native. I took a pass at updating it and submitted a PR here: https://github.com/ant-design/ant-design-pro-site/pull/112

I don't understand Chinese but as a native Californian I am happy to help with translation however I can. :)

**Comment by gardner** [comment]
The current way the docs are organized leaves a little to be desired. I am new to bisheng so I will read up on it and see if there is a way to modularize translations a bit better. I know some folks that may be able to help out with other languages.

**Comment by sundaisun** [comment]
Hi, just came across ant design pro, great work! I am a product designer on the Design System team at Eventbrite, based in San Francisco, and would like to help translating `layout.md`. Let me know :)

**Comment by viztor** [comment]
@sundaisun Hi, already working on Layout.md. Forgot to mention it here.
also i18n.md and cli.md is ready for review.

**Comment by priezz** [comment]
Hello! First of all, thanks for the great template!

This issue is about document translation, but I don't want to open the separate one for the template translation. I have written a short script to automatically translate the cloned template into English with Google. Here it is:

```
REGEXP='\p{Han}[\p{Han}|\s|,|。|，|\.|“|”|0-9|a-z|A-Z|-|-|:|：]*'; 
rg --color never "$REGEXP" -o --vimgrep src | sed -r "s|([^:]+):([^:]+):([^:]+):(.+)|STR='\4'; sed -i \"\2s/\$STR/\$\(translate --brief zh:en \\\"\$STR\\\"\)/\" $(pwd)/\1;|g" > /tmp/translate.sh;
sh /tmp/translate.sh;
```
Dependencies: [Translate Shell](https://www.soimort.org/translate-shell), [ripgrep](https://github.com/BurntSushi/ripgrep)

The result is rather acceptable - translation is not ideal, of course, but at lease it enables Chinese non-speaker to start with.

Hope it helps to someone :)

**Comment by davidctj** [comment]
Hi, thanks for providing such amazing ant design pro! 
I'm a frontend developer who has been using ant design a lot, love it!
I'd like to translate on  faq.md && theme.md

**Comment by B1anker** [comment]
Can CET-6 make a try？

**Comment by chenshuai2144** [comment]
@B1anker   Of course.
you can translate and then pr

**Comment by xueqingxiao** [comment]
I can take `biz-icon.md`, ` deploy.md`, `error.md`, `faq.md`.

**Comment by bunshar** [comment]
I can help in making demos in english. In ant-design the demos have data in english  and I can convert that within week if it's required.

**Comment by chenshuai2144** [comment]
@bunshar  当然需要了

**Comment by priezz** [comment]
@bunshar, my script above (to be specific, it's third line) transtales demo data as well. For me it seems that it could be too early for the fine tuned manual translation as the product is still in active development stage. However, I could be wrong :)

**Comment by lorecrafting** [comment]
Hello, I would like to help with translation.  Are you folks trying to get all the documentation translation done by the time Ant Pro 1.0 is released?

Also i'm currently translating the Ant Pro component data, and also mock data so that the Dashboard can be displayed in English.  Should I put the translation of mock data and ant pro sample components in a new 'english' branch? 
@nikogu 

Thanks!

**Comment by lorecrafting** [comment]
I will start translating components in the ant-design-pro repo, going to start with Charts!

**Comment by bunshar** [comment]
Nice script @priezz !
Needed some changes to get it to run in Mac so sharing that

Translate script for mac users as sed in mac is not same as sed in gnu

install with -  `brew install --with-default-names gnu-sed `
and then use that. Also the `translate` doesn't work but `trans` does
```
REGEXP='\p{Han}[\p{Han}|\s|,|。|，|\.|“|”|0-9|a-z|A-Z|-|-|:|：]*'; 
rg --color never "$REGEXP" -o --vimgrep src | gsed -r "s|([^:]+):([^:]+):([^:]+):(.+)|STR='\4'; gsed -i \"\2s/\$STR/\$\(trans --brief zh:en \\\"\$STR\\\"\)/\" $(pwd)/\1;|g" > /tmp/translate.sh;
rg --color never "$REGEXP" -o --vimgrep mock | gsed -r "s|([^:]+):([^:]+):([^:]+):(.+)|STR='\4'; gsed -i \"\2s/\$STR/\$\(trans --brief zh:en \\\"\$STR\\\"\)/\" $(pwd)/\1;|g" >> /tmp/translate.sh;
sh /tmp/translate.sh;
```

**Comment by priezz** [comment]
@bunshar, thank you for your addition! You are right, unfortunately mac's `sed` is not gnu-compatible.
However, but with `--with-default-names` option, you have provided, `brew` installs `sed` without `g` in the front. So the script stays unchanged. I also update `translate` to `trans` in the initial script as it is their recommended command name.

**Comment by bunshar** [comment]
The issue is that this breaks my ability to keep the repo in sync as there are so many changes. 

I think this is the right time to start translation. The script is a good starting point and will save quite a lot of effort.

**Comment by ddcat1115** [comment]
@lorecrafting  The Ant Design Pro 1.0 do not rely on the translation work, and only some of the guide docs may be changed after the 1.0 release. As for components, you can start your translation at anytime 😃

**Comment by ZiyiFeng-SJSU** [comment]
I can help on " use-components-alone.md" translation if it is not taken yet. And thank you for the great framework!

**Comment by vtista** [comment]
@afc163 I'd Like to join the translation team!☺☺☺

**Comment by crunchysoul** [comment]
I would love to be a translator for this project, really enjoy antd and antdpro, want to contribute more.

**Comment by ddcat1115** [comment]
Some docs have been updated(since v1.0) and we can restart our translation 💦

**Comment by richardzyx** [comment]
Can we start a Trello board to keep track of the translation effort between multiple versions and projects? Having to track down PRs and issues just to find the latest work progress is simply not efficient, and here is case study of how Trello used Trello to manage the translation process: http://www.oneskyapp.com/blog/trello-localization-global-marketing/

The issues in ant-design repo seem to reference this issue for tracking the translation of specs as well? I'm just lost in the translation works for ant-design spec, ant-design components, and ant-design pro. Having a globally accessible Trello should help a lot with this process.

Thanks!

**Comment by NickFranceschina** [comment]
I am also a big fan and and native English speaker and happy to help where I can.  I should have already forked this repo before starting my latest project, but will do so now.  Thank you for your great effort!

**Comment by SimpleFrontend** [comment]
Hi, just translated the Login component and sent PR, will pick up more later :-)

**Comment by tchern** [comment]
I'd love to help with both review and translation. I am a technical writer, English native and Chinese bilingual writing and reading proficiency. I can start with reviewing [/docs/layout.md](https://github.com/ant-design/ant-design-pro-site/blob/master/docs/layout.en-US.md) and  [components/AvartarList.md](https://github.com/ant-design/ant-design-pro/blob/master/src/components/AvatarList/index.en-US.md).  I also spotted a few small grammar errors in [getting-started.md](https://github.com/ant-design/ant-design-pro-site/blob/master/docs/getting-start-inner.en-US.md), if you'd like me to correct that too. 

我可以帮忙中英翻译和修改英文的版本。上面列了几个md是我可以先修改的。 （我英文中文双语，繁体中文和简体中文都能专业读写）

**Comment by ddcat1115** [comment]
@tchern You are very welcome! But the `/docs/layout` and `components/AvatarList.md` is translated and reviewed already(you can check the TODOs progress in [above](https://github.com/ant-design/ant-design-pro/issues/120#issue-271422911)), you can help us to translate the other parts, just mark your name after the item you have chosen. Or you can join the review work -> [to be reviewed](https://github.com/ant-design/ant-design-pro-site/pulls)

**Comment by atav32** [comment]
Sign me up. I'll help translate.

**Comment by meluo** [comment]
Module build failed: Error: Cannot use decorators and decorators2 plugin together

**Comment by sroze** [comment]
Thank you all for your translation efforts. This seems to be a very nice set of UI elements ❤️

**Comment by cyw1361546576** [comment]
我渴望找到一份自己喜欢并热爱的工作，希望你们能帮帮我，也许我会有不懂不会的，但是我会努力去学，谢谢。

**Comment by cyw1361546576** [comment]
I am eager to find a job I like and love, I hope you can help me, maybe I will not understand, but I will try to learn, thank you.

**Comment by zhuzisheng** [comment]
I can help translate the login part into English.

**Comment by maria-le** [comment]
Google Translate does a pretty good job doesn't it? Why not just use that?

**Comment by chloesun** [comment]
I can help with some translation as well, feel free to reach out and let me know what pieces I can work on!

**Comment by robsonsilv4** [comment]
I added README in portuguese (pt-BR), see #5438.
And i will also help to translate documentation to portuguese.

**Comment by BoyoJustice** [comment]
I would be happy to be a reviewer of "router-and-nav.md" if still available.

**Comment by cyw1361546576** [comment]
ok  
---原始邮件---
发件人:"Garrett Beyer"<notifications@github.com>
发送时间:2019年11月30日 星期六 下午8:1
收件人:"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>
抄送:"cyw1361546576"<1361546576@qq.com>;"Comment"<comment@noreply.github.com>
主题:Re: [ant-design/ant-design-pro] Document Translation (#120)

I would be happy to be a reviewer of "router-and-nav.md" if still available.

&mdash;

**Comment by nelsonacalves** [comment]
> We just finished most of translate jobs and published at [pro.ant.design](http://pro.ant.design), welcome to visit it and review the translation. Give us PR if you find any typos. 🎅
> 
> ## Volunteer Wanted
> Hey, guys! We are going to provide English documentation.
> 
> But we are short of staff :-( So, we want some volunteers to help us to translate antd's documentation into English. Every translation task needs a translator and a reviewer. Both of them are expected that they had used the component(`AvatarLsit` `PageHeader` etc...) in real world.
> 
> ### Translator
> A translator should be familiar with both Chinese and English.
> 
> If you want to be a volunteer translator, just comment this issue. For example, "I want to be the translator of button and alert ....". And then, we will update this issue(e.g. button (translator: @afc163 , reviewer: @ddcat1115 )), and ping you.
> 
> Premise:
> 
> * [ant-design-pro-site](https://github.com/ant-design/ant-design-pro-site) is our site of Ant Design Pro and it is repository witch docs here.
> * [ant-design-pro](https://github.com/ant-design/ant-design-pro) is [ant-design-pro-site](https://github.com/ant-design/ant-design-pro-site)'s submodule, it contains component's docs.
> 
> Contributing:
> 
> 1. Fork
>    
>    * docs: [ant-design-pro-site](https://github.com/ant-design/ant-design-pro-site) and `git clone`
>    * components: [ant-design-pro](https://github.com/ant-design/ant-design-pro) and `git clone`
> 2. Create a branch starting at `master` and name it as `translation-[xxx]`
> 3. `npm install && npm start`, see: [Development](https://github.com/ant-design/ant-design-pro-site#development)
> 4. Find Markdown files and the `index.md` and `demo/*.md` use different format, see: [ant-design/ant-design#1423](https://github.com/ant-design/ant-design/issues/1423)
>    
>    * docs: under `/docs`
>    * components: under `/scaffold/src/components/xxx`(xxx is the component which you need to translate)
> 5. Just translate it, and you had better read our [advice](https://github.com/ant-design/ant-design/issues/1471#issuecomment-213636139) first.
> 6. Create a pull request when your translation is done, and ping your reviewer.
>    
>    * docs: request to `ant-design-pro-site:master`
>    * components: request to `ant-design-pro:master`
> 7. PR will be merged, if your reviewer think it is OK.
> 
> See:
> 
> * https://github.com/ant-design/ant-design/tree/master/components/button
> * https://github.com/ant-design/ant-design/blob/master/components/button/demo/basic.md
> 
> ### Reviewer
> A reviewer should be a native English speaker.
> 
> If you want to be a volunteer reviewer, just comment this issue. For example, "I want to be the reviewer of button and alert...". And then, we will update this issue(e.g. button (translator: @afc163 , reviewer: @ddcat1115 )), and ping you.
> 
> After your corresponding translator finish his/her work, you should review and provide some advice.
> 
> ### Example
> * docs: [105](https://github.com/ant-design/ant-design-pro-site/pull/105)
> * components: [123](https://github.com/ant-design/ant-design-pro/pull/123)
> 
> ### TODOs
> /docs
> 
> * [x]  api-doc.md ( translator: @yesmeck )
> * [ ]  authority-management.md ( translator: @chenshuai2144 )
> * [ ]  biz-icon.md ( translator: @ddcat1115 )
> * [ ]  changelog.md ( translator: @ddcat1115 )
> * [x]  cli.md ( translator: @viztor )
> * [x]  deploy.md  ( translator: @yesmeck )
> * [ ]  error.md ( translator: @nikogu )
> * [ ]  faq.md ( translator: null)
> * [x]  getting-started.md
> * [x]  getting-start-inner.md
> * [ ]  graph.md (translator: @RaoHai)
> * [x]  i18n.md ( translator: @viztor )
> * [ ]  import.md ( translator: null)
> * [x]  layout.md ( translator: @viztor )
> * [ ]  mock-api.md ( translator: @afc163 ) [ant-design/ant-design-pro-site#156](https://github.com/ant-design/ant-design-pro-site/pull/156)
> * [x]  new-component.md ( translator: @afc163 ) [ant-design/ant-design-pro-site#157](https://github.com/ant-design/ant-design-pro-site/pull/157)
> * [x]  new-page.md ( translator: @valleykid )
> * [x]  resource.md ( translator: @nikogu )
> * [ ]  router-and-nav.md ( translator: @ddcat1115 )
> * [x]  server.md ( translator: @valleykid )
> * [x]  style.md( translator: @yutingzhao1991 ) [ant-design/ant-design-pro-site#148](https://github.com/ant-design/ant-design-pro-site/pull/148)
> * [ ]  theme.md ( translator: @nikogu )
> * [ ]  ui-test.md ( translator: @yutingzhao1991 ) [ant-design/ant-design-pro-site#151](https://github.com/ant-design/ant-design-pro-site/pull/151)
> * [x]  use-components-alone.md ( translator: @dengfuping )
> 
> /components
> 
> * [x]  AvatarList (translator: @nikogu)
> * [ ]  Charts (translator: @RaoHai)
> * [x]  CountDown (translator: @nikogu)
> * [x]  DescriptionList ( translator: @ddcat1115 )
> * [x]  Exception ( translator: @ddcat1115 )
> * [x]  FooterToolbar ( translator: @dengfuping )
> * [ ]  GlobalFooter ( translator: @MrPeak  )
> * [ ]  HeaderSearch ( translator: @MrPeak  )
> * [ ]  NoticeIcon ( translator: @MrPeak  )
> * [x]  NumberInfo
> * [x]  Ellipsis
> * [ ]  PageHeader
> * [ ]  Result
> * [ ]  TagSelect
> * [ ]  Trend
> * [ ]  Authorized ( translator: @chenshuai2144 )
> * [ ]  Login

So,
How can i help translate?
 what work is available?

**Comment by smzto** [comment]
I'm a brazilian developer and I want to join this.
I want to help translate it, but in **portuguese**, we have a large dev market in ascension here.
By the way, it will be a nice contribution for all.

**Comment by Gamatrox33** [comment]
Hello when are you going to translate Ant Design into French?
