### ISSUE TITLE
Preparing 1.0.0

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro#333]
- [x] Upgrade Ant Design v3.0 https://github.com/ant-design/ant-design/issues/8337
- [x] Upgrade Charts to BizCharts https://github.com/ant-design/ant-design-pro/issues/296 @nikogu 
- [x] Support authorized menu https://github.com/ant-design/ant-design-pro/issues/41 @ddcat1115 
- [x] Refactor router/menu config https://github.com/ant-design/ant-design-pro/issues/394 @ddcat1115 
- [ ] Support Typescript https://github.com/ant-design/ant-design-pro/issues/93 @chenshuai2144 
- [ ] Ensure all issues labeled by v1 are resolved [v1 issue](https://github.com/ant-design/ant-design-pro/issues?q=is%3Aopen+is%3Aissue+label%3Av1)

@ddcat1115 @afc163 @WhatAKitty @chenshuai2144 @valleykid @yesmeck  take a look

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/304
https://github.com/ant-design/ant-design-pro/issues/298

**Comment by WhatAKitty** [comment]
#338

**Comment by tyyzqmf** [comment]
1.0.0版本预计什么时候出？

**Comment by chenshuai2144** [comment]
@tyyzqmf 按照这个进度 最少一个月吧

**Comment by kaoding** [comment]
先得等发antd v3.0正式版发布了才有时间发发antd pro v1.0.0吧。

**Comment by chenshuai2144** [comment]
支持组件的d.ts已经完成了!
应该不会再修改api了吧

**Comment by kaoding** [comment]
相对于antd v3.0来说，更期待antd pro v1.0.0的发布，在规划中的产品等着正式使用pro。

**Comment by chenshuai2144** [comment]
@kaoding  我现在就在用.已经可以使用了.功能可以自己实现的.

**Comment by kaoding** [comment]
我现在是试用，在我们正式的产品中，还是要等tntd pro团队发布稳定版本的v1.0.0再说。 @chenshuai2144

**Comment by kaoding** [comment]
antd pro的推出，对于我们这样的小公司来说，可以把以前要三个人做的事（产品[Axure]( http://library.ant.design/)，设计，前端开发）、压缩到一个人能力强的来做。

**Comment by nikogu** [comment]
@tyyzqmf @chenshuai2144 下周 authorized menu 和 charts 就会搞完，争取下周发布

**Comment by sillyfeng** [comment]
6666

**Comment by sillyfeng** [comment]
@nikogu 给老铁打call

**Comment by woshiguabi** [comment]
@nikogu 老铁加油，项目就等着这个发布了

**Comment by mcmf** [comment]
下周都好久了    好期待 早日发布正式版

**Comment by WhatAKitty** [comment]
估计还需要个至少一周的时间，调整路由以及授权支持估计还需要花比较长的时间。

**Comment by afc163** [comment]
今天能搞定么？@ddcat1115

**Comment by sillyfeng** [comment]
时刻关注着。。

**Comment by DingLiPlus** [comment]
> 时刻关注着。。

看来马上就要发布了

**Comment by kaoding** [comment]
v1.0好期待，老铁们加油！

**Comment by sillyfeng** [comment]
@kaoding  猛地一下看见，还以为是1.0发布了。。。。。。

**Comment by doterme** [comment]
下周能发1.0么？

**Comment by tomgao365** [comment]
围观和观望中

**Comment by ddcat1115** [comment]
### 1.0.0

`2018-01-10`

- 脚手架
  - 🌟 图表底层升级 BizCharts，修复了之前的一些问题，更新了部分 UI。[#370](https://github.com/ant-design/ant-design-pro/pull/370)
  - 🌟 采用全新的菜单及路由配置，能够支持更多更灵活的需求场景，修复了之前存在的一些问题，同时支持指定菜单项/面包屑隐藏。[#442](https://github.com/ant-design/ant-design-pro/pull/442)
  - 🌟 增加权限管理模块，支持通过简单的简单的配置，实现基本的权限管理需求。[#508](https://github.com/ant-design/ant-design-pro/pull/508)
  - 🌟 升级 Roadhog@2，支持 code split 配置化。[#542](https://github.com/ant-design/ant-design-pro/pull/542) [#562](https://github.com/ant-design/ant-design-pro/pull/562)
  - 🌟 增加全局异常处理。[#500](https://github.com/ant-design/ant-design-pro/pull/500)
  - 🌟 增加 dva-loading，去掉了一堆 loading 处理。[#587](https://github.com/ant-design/ant-design-pro/pull/587)
  - 🌟 扩展dymaicWrapper，防止Model重复导入报错。[#506](https://github.com/ant-design/ant-design-pro/issues/506)

- 组件
  - 🌟 新增 Login 组件 [147](https://github.com/ant-design/ant-design-pro/pull/147)
  - 🌟 针对手机端进行了 SiderMenu 的优化。[463](https://github.com/ant-design/ant-design-pro/pull/463)
 
---
...to be continued

**Comment by afc163** [comment]
简单的简单的

**Comment by chenshuai2144** [comment]
文档还没写好

**Comment by sillyfeng** [comment]
哇，终于可以安心了。。。。666

**Comment by ddcat1115** [comment]
@chenshuai2144 哪个文档？路由和权限都提交到 site 了，可以看下有没补充的

**Comment by chenshuai2144** [comment]
文档比较少！ 我跑不起来site 没有 demo

**Comment by ddcat1115** [comment]
觉得文档哪儿欠缺可以直接补充哈~

**Comment by chenshuai2144** [comment]
恩。我今天提交了几个 你帮忙看看对不对

**Comment by soolx** [comment]
今天会发布V1.0吗，期待中啊

**Comment by afc163** [comment]
旧版文档：http://03x.pro.ant.design/

**Comment by zqqq** [comment]
关注

**Comment by cuihairu** [comment]
万分感谢，拜读

**Comment by ddcat1115** [comment]
[changelog 1.0.0](https://pro.ant.design/docs/changelog#1.0.0-%F0%9F%8E%86)

**Comment by chenshuai2144** [comment]
已经没有v1的标签了
