### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#4389]
- [x] 支持 ts 区块转 js https://github.com/umijs/umi/pull/2554
- [x] 黑色主题 beta 版本 https://github.com/ant-design/ant-design-pro/pull/4356
- [x] 使用 eslint-typescript，提升代码质量 https://github.com/ant-design/ant-design-pro/pull/4336
- [x] 永远需要更多的文档

------------
- [x] Support ts block to js  https://github.com/umijs/umi/pull/2554
- [x] Black theme beta version https://github.com/ant-design/ant-design-pro/pull/4356
- [x] Use eslint-typescript to improve code quality https://github.com/ant-design/ant-design-pro/pull/4336
- [x] Always need more documentation

**Comment by tomgao365** [comment]
👏 期待黑色主题以及可以在正式版使用主题切换。

**Comment by kaoding** [comment]
都需要

**Comment by doterme** [comment]
有计划出新的layout吗？

**Comment by chenshuai2144** [comment]
>  @doterme  有计划出新的layout吗？

有新需求可以新建 issue 跟进一下.

**Comment by kaoding** [comment]
ant design pro 后续有大版本的计划吗?

**Comment by ShawDanon** [comment]
权限支持到按钮级？

**Comment by mushroomlb** [comment]
有计划出一个升级工具吗，从2升级到4

**Comment by yinxiaoling** [comment]
浏览器兼容性的问题真的是重中之重的计划，舍弃掉太可惜了，如果做上，国内做2B的估计都会选择此脚手架了，目前望而却步，望洋兴叹。
