### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by dbucci24** [ant-design/ant-design-pro#951]
Hello! I would like to translate the project into Spanish! is it already translated?

**Comment by chenshuai2144** [comment]
No.
Start to do it.

**Comment by dbucci24** [comment]
@chenshuai2144  What files can I translate?

**Comment by chenshuai2144** [comment]
### TODOs

/docs
- [ ] api-doc.md 
- [ ] authority-management.md 
- [ ] biz-icon.md 
- [ ] changelog.md 
- [x] cli.md 
- [ ] deploy.md 
- [ ] error.md 
- [ ] faq.md
- [] getting-started.md
- [] getting-start-inner.md
- [ ] graph.md 
- [] i18n.md 
- [ ] import.md 
- [] layout.md 
- [ ] mock-api.md
- [ ] new-component.md
- [ ] new-page.md
- [x] resource.md 
- [ ] router-and-nav.md 
- [ ] server.md
- [ ] style.md
- [ ] theme.md 
- [ ] ui-test.md 
- [ ] use-components-alone.md 

/components
- [] AvatarList 
- [ ] Charts 
- [] CountDown
- [ ] DescriptionList 
- [ ] Exception
- [ ] FooterToolbar 
- [ ] GlobalFooter 
- [ ] HeaderSearch
- [ ] NoticeIcon
- [ ] NumberInfo
- [ ] Ellipsis
- [ ] PageHeader
- [ ] Result
- [ ] TagSelect
- [ ] Trend
- [ ] Authorized
- [ ] Login

**Comment by dbucci24** [comment]
Should I translate it from Chinese to Spanish? There are no English files so i can translate from English into Spanish?

**Comment by yesmeck** [comment]
@dbucci24 We may only have the energy to maintain the Chinese and English document, see https://github.com/ant-design/ant-design/issues/8505#issuecomment-350063804
